### ISSUE TITLE
System scaling using helm chart

### ISSUE THREAD

**Issue by abhatiwa-bh** [SolaceProducts/pubsubplus-kubernetes-helm-quickstart#118]
Description:

I have configured solace in my dev env(using helm chart) and currently it only allows upto 100 queues/endpoints creation. To scale I tried setting systemScaling values to :
![image](https://user-images.githubusercontent.com/99185435/222091700-39aeb83a-ffec-4bcf-96b1-5c7077edbb4f.png)

But it doesn't seem to be working.

I setup solace in my laptop in docker and added these as --env system_scaling_maxconnectioncount=1000 --env system_scaling_maxqueuemessagecount=1000 --env messagespool_maxspoolusage=1000

Here, it seems to have worked in my laptop.
But in dev env using helm chart, it doesn't seem to be working.

**Comment by bczoma** [comment]
Hi @abhatiwa-bh ,

There is a difference between scaling up an existing deployment or scaling for an initial deployment.

When you deployed on your laptop and it worked it was an initial deployment.

Due to Helm limits, scaling up an existing deployment is a two-step process. The first step is, as you tried, to update the deployment with the new parameters. While this shall result in larger CPU and memory for the broker pod after restart, it requires a second step to actually scale up the broker, as described here: https://github.com/SolaceProducts/pubsubplus-kubernetes-quickstart/blob/master/docs/PubSubPlusK8SDeployment.md#comprehensive-vertical-scaling

So for the second step, [access the broker CLI](https://github.com/SolaceProducts/pubsubplus-kubernetes-quickstart/blob/master/docs/PubSubPlusK8SDeployment.md#solace-cli-access) and manually follow the process from the Solace documentation: https://docs.solace.com/Software-Broker/Set-Scaling-Params-HA.htm (even for the single broker in non-HA deployment).

Hope this helps!

**Comment by bczoma** [comment]
Closing as the scaling up process has been documented, see:
https://github.com/SolaceProducts/pubsubplus-kubernetes-quickstart/blob/main/docs/EventBrokerOperatorUserGuide.md#node-assignment
