### ISSUE TITLE
Running two instances crashes my cluster

### ISSUE THREAD

**Issue by Jonathan-Eid** [SolaceProducts/pubsubplus-kubernetes-helm-quickstart#83]
I would like to have two separate brokers on my cluster. I can have one broker pod spinning up just fine and that doesn't affect any other containers on my cluster. However, when I introduce another broker pod into the cluster, every other container on the cluster just starts crashing. Any ideas? 

These are the startup commands I am using:

helm install --name solace0 solacecharts/pubsubplus --set storage.useStorageClass=fast-rbd,storage.nfs=false,storage.size=16Gi,solace.size=prod1k,solace.usernameAdminPassword=password

helm install --name solace1 solacecharts/pubsubplus --set storage.useStorageClass=fast-rbd,storage.nfs=false,storage.size=16Gi,solace.size=prod1k,solace.usernameAdminPassword=password

**Comment by bczoma** [comment]
Hi Jonathan, wondering if deploying the second broker exhausts the kubernets cluster nodes CPU/memory resources. You can check this by trying to deploy a minimum footprint broker: specify `--set solace.size=dev` instead of prod1k and also `kubectl describe` the node(s) and check available resources. It may have to do with the storage - does it dynamically allocate unused and enough storage for the second cluster? Also check before deployment if a PVC from an earlier same named deployment already exists and the new broker inadvertently tries to reuse the database from a prev deployment.

**Comment by Jonathan-Eid** [comment]
--set solace.size=dev was the way to go, thank you!
